class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror1'
        self.UnzipMirrorCommand = 'unzipmirror1'
        self.TarMirrorCommand = 'tarmirror1'
        self.ZipMirrorCommand = 'zipmirror1'
        self.CancelMirror = 'cancel1'
        self.CancelAllCommand = 'cancelall1'
        self.ListCommand = 'list'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize1'
        self.UnAuthorizeCommand = 'unauthorize1'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart1'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone1'
        self.CountCommand = 'count1'
        self.WatchCommand = 'watch1'
        self.TarWatchCommand = 'tarwatch1'
        self.DeleteCommand = 'del1'
        self.ConfigMenuCommand = 'config1'
        self.ShellCommand = 'shell1'
        self.UpdateCommand = 'update'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp1'
        self.UsageCommand = 'usage'

BotCommands = _BotCommands()
